name: mbd-nm-captive
base: core22
adopt-info: nm-captive
summary: Listens for changes in network connectivity state
description: |
  This program will print a message whenever NetworkManager detects a captive portal
grade: stable
confinement: strict

parts:
  nm-captive:
    build-snaps:
      - go
    plugin: go
    source: .
    override-pull: |
      craftctl default
      craftctl set version="$(git rev-parse --short HEAD)"

apps:
  nm-captive:
    command: bin/nm-captive

plugs:
  nm-link:
    interface: network-manager
  netcontrol:
    interface: network-control
